source 'http://rubygems.org'
#gem 'github-pages'
gem 'github-pages-health-check' ,'~> 0.2'
gem 'jekyll' ,'= 2.4.0'
gem 'jekyll-coffeescript' ,'= 1.0.1'
gem 'jekyll-mentions', '= 0.2.1'
gem 'jekyll-redirect-from', '= 0.6.2'
gem 'jekyll-sass-converter', '= 1.2.0'
gem 'jekyll-sitemap', '= 0.6.3'
gem 'jemoji', '= 0.4.0'
gem 'kramdown' ,'= 1.5.0'
gem 'liquid', '= 2.6.1'
gem 'maruku', '= 0.7.0'
gem 'mercenary', '~> 0.3'
gem 'pygments.rb' ,'= 0.6.1'
#rdiscount = 2.1.7
gem 'redcarpet', '= 3.1.2'
gem 'RedCloth', '= 4.2.9'
gem 'terminal-table', '~> 1.4'